AWSTemplateFormatVersion: 2010-09-09
Description: DeployStack CFN template translated from Docker compose
Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetA:
    Type: AWS::EC2::Subnet::Id
  SubnetB:
    Type: AWS::EC2::Subnet::Id
  ServiceName:
    Type: String
    Default: DeployStackService
Resources:
  Cluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Join ['', [!Ref ServiceName, Cluster]]
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Join ['', [!Ref ServiceName, ExecutionRole]]
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
  LogGrouppassky-server:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ['', [/ecs/, !Ref ServiceName, TaskDefinitionpassky-server]]
  TaskDefinitionpassky-server:
    Type: AWS::ECS::TaskDefinition
    DependsOn:
      - LogGrouppassky-server
    Properties:
      Family: !Join ['', [!Ref ServiceName, TaskDefinitionpassky-server]]
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 512
      Memory: 1GB
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: passky-server
          Image: docker.io/rabbitcompany/passky-server:latest
          ReadonlyRootFilesystem: false
          PortMappings:
            - ContainerPort: 80
          Environment:
            - name: SERVER_LOCATION
              value: ""
            - name: SERVER_CORES
              value: ""
            - name: ADMIN_USERNAME
              value: ""
            - name: ADMIN_PASSWORD
              value: ""
            - name: CF_TURNSTILE_SITE_KEY
              value: ""
            - name: CF_TURNSTILE_SECRET_KEY
              value: ""
            - name: DATABASE_ENGINE
              value: ""
            - name: DATABASE_FILE
              value: ""
            - name: MYSQL_HOST
              value: ""
            - name: MYSQL_PORT
              value: ""
            - name: MYSQL_DATABASE
              value: ""
            - name: MYSQL_USER
              value: ""
            - name: MYSQL_PASSWORD
              value: ""
            - name: MYSQL_SSL
              value: ""
            - name: MYSQL_SSL_CA
              value: ""
            - name: MYSQL_CACHE_MODE
              value: ""
            - name: REDIS_HOST
              value: ""
            - name: REDIS_PORT
              value: ""
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_LOCAL_HOST
              value: ""
            - name: REDIS_LOCAL_PORT
              value: ""
            - name: REDIS_LOCAL_PASSWORD
              value: ""
            - name: MAIL_ENABLED
              value: ""
            - name: MAIL_HOST
              value: ""
            - name: MAIL_PORT
              value: ""
            - name: MAIL_USERNAME
              value: ""
            - name: MAIL_PASSWORD
              value: ""
            - name: MAIL_USE_TLS
              value: ""
            - name: ACCOUNT_MAX
              value: ""
            - name: ACCOUNT_MAX_PASSWORDS
              value: ""
            - name: ACCOUNT_PREMIUM
              value: ""
            - name: YUBI_CLOUD
              value: ""
            - name: YUBI_ID
              value: ""
            - name: LIMITER_ENABLED
              value: ""
            - name: LIMITER_GET_INFO
              value: ""
            - name: LIMITER_GET_STATS
              value: ""
            - name: LIMITER_GET_TOKEN
              value: ""
            - name: LIMITER_GET_PASSWORDS
              value: ""
            - name: LIMITER_SAVE_PASSWORD
              value: ""
            - name: LIMITER_EDIT_PASSWORD
              value: ""
            - name: LIMITER_DELETE_PASSWORD
              value: ""
            - name: LIMITER_DELETE_PASSWORDS
              value: ""
            - name: LIMITER_CREATE_ACCOUNT
              value: ""
            - name: LIMITER_DELETE_ACCOUNT
              value: ""
            - name: LIMITER_IMPORT_PASSWORDS
              value: ""
            - name: LIMITER_FORGOT_USERNAME
              value: ""
            - name: LIMITER_ENABLE_2FA
              value: ""
            - name: LIMITER_DISABLE_2FA
              value: ""
            - name: LIMITER_ADD_YUBIKEY
              value: ""
            - name: LIMITER_REMOVE_YUBIKEY
              value: ""
            - name: LIMITER_UPGRADE_ACCOUNT
              value: ""
            - name: LIMITER_GET_REPORT
              value: ""
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-region: !Ref AWS::Region
              awslogs-group: !Ref LogGrouppassky-server
              awslogs-stream-prefix: ecs
  ContainerSecurityGrouppassky-server:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Join ['', [passky-server, ContainerSecurityGroup]]
      VpcId: !Ref VPC
      SecurityGroupIngress:
        IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0
  Servicepassky-server:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: passky-server
      Cluster: !Ref Cluster
      TaskDefinition: !Ref TaskDefinitionpassky-server
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref SubnetA
            - !Ref SubnetB
          SecurityGroups:
            - !Ref ContainerSecurityGrouppassky-server
