version: "3"
services:
  fathom:
    image: usefathom/fathom:latest
    ports:
      - "8080:8080"
    environment:
      - "FATHOM_SERVER_ADDR=:8080"
      - "FATHOM_GZIP=true"
      - "FATHOM_DEBUG=false"
      - "FATHOM_DATABASE_DRIVER=sqlite3"
      - "FATHOM_SECRET=TWEn6GXQDx45PZfmJWvyGpXf5M8b94bszgw8JcJWEd6WxgrnUkLatS34GwjPTvZb"
    restart: always
