services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/marcobaobao/yt-dlp-webui:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "3033"
    disk:
      name: default-downloads
      mountPath: /downloads
      sizeGB: 10
