services:
  - name: fathom
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/usefathom/fathom:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: FATHOM_SERVER_ADDR
        value: :8080
      - key: FATHOM_GZIP
        value: "true"
      - key: FATHOM_DEBUG
        value: "false"
      - key: FATHOM_DATABASE_DRIVER
        value: sqlite3
      - key: FATHOM_SECRET
        value: TWEn6GXQDx45PZfmJWvyGpXf5M8b94bszgw8JcJWEd6WxgrnUkLatS34GwjPTvZb
      - key: PORT
        value: "8080"
