services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/baserow/baserow:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: BASEROW_PUBLIC_URL
        value: http://localhost
      - key: DISABLE_VOLUME_CHECK
        value: yes
      - key: PORT
        value: "80"
