services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/yourselfhosted/slash:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "5231"
    disk:
      name: default-var-opt-slash
      mountPath: /var/opt/slash
      sizeGB: 10
