version: '3'
services:
  passky-server:
    container_name: passky-server
    image: 'rabbitcompany/passky-server:latest'
    restart: unless-stopped
    environment:
      - ADMIN_USERNAME="admin"
      - ADMIN_PASSWORD="admin_password"
      - DATABASE_ENGINE="sqlite"
    ports:
      - 8080:80
    volumes:
      - ./databases:/var/www/html/databases
