services:
  - name: passky-server
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/rabbitcompany/passky-server:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: ADMIN_USERNAME
        value: ""
      - key: ADMIN_PASSWORD
        value: ""
      - key: DATABASE_ENGINE
        value: ""
      - key: PORT
        value: "80"
    disk:
      name: passky-server-var-www-html-databases
      mountPath: /var/www/html/databases
      sizeGB: 10
