services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/ananthakumaran/paisa:latest
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "7500"
