services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/neosmemo/memos:stable
    startCommand: ""
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: "5230"
