services:
  - name: default
    type: web
    env: docker
    runtime: image
    image:
      url: docker.io/blukat29/libc:latest
    startCommand: ""
    plan: starter
    region: oregon
    envVars:
      - key: PORT
        value: "80"
